"""
Django settings for acserver project.

Generated by 'django-admin startproject' using Django 1.8.14.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=vk51q56fo-b2yfr(8uhdg8m^o)v53k9=wvti=$nn^+26w_f3e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = (
    'flat',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'constance',
    'constance.backends.database',
    'bootstrap3',
    'formtools',
    'background_task',
    'smart_selects',
    'library',
    'session',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'acserver.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'acserver.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/usr/local/ACServerManager/static'
MEDIA_ROOT = '/usr/local/ACServerManager/media'


REST_FRAMEWORK = {
#    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAdminUser',),
    'PAGE_SIZE': 10
}


MINORATING_GRADE_CHOICES = (
    ('A', 'A - exemplary'),
    ('AB', 'AB - clean racer (or better)'),
    ('ABC', 'ABC - rookie (or better)'),
    ('ABCN', 'ABCN - rookie or new/unlisted racers (or better)'),
    ('ABCDN', 'ABCDN - dirty racers welcome'),
    ('ABCDNW', 'ABCDNW - anybody (including wreckers)'),
)

CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

CONSTANCE_ADDITIONAL_FIELDS = {
    'mr_grade_choices': ['django.forms.fields.ChoiceField', {
        'widget': 'django.forms.Select',
        'choices': (
            ('A', 'A - exemplary'),
            ('AB', 'AB - clean racer (or better)'),
            ('ABC', 'ABC - rookie (or better)'),
            ('ABCN', 'ABCN - rookie or new/unlisted racers (or better)'),
            ('ABCDN', 'ABCDN - dirty racers welcome'),
            ('ABCDNW', 'ABCDNW - anybody (including wreckers)'),
        )
    }],
}

CONSTANCE_CONFIG = {
    'name': ('Meekys AC Server', 'The name of the server - this will appear in the Assetto Corsa\'s listing of online servers for the public to join', str),
    'welcome_message': ('Hello there!', 'Place a welcome message here - this will display some dialog to clients upon joining a session which they must click to close', str),
    'admin_password': ('changeme', 'Server Admin Password - joining the session using this password grants the user admin privilges (allowing you to skip sessions, kick users, etc)', str),
    'minorating_grade': ('ABCN', 'Minorating Grade required to join this server\'s sessions (driver proficiency - see http://www.minorating.com/Grades for details)', 'mr_grade_choices'),
    'udp_port': (9600, 'Assetto Corsa server UDP port number', int),
    'tcp_port': (9600, 'Assetto Corsa server TCP port number', int),
    'http_port': (8081, 'Lobby port number', int),
    'send_buffer_size': (0, 'DOCUMENTATION SOURCE NEEDED', int),
    'recv_buffer_size': (0, 'DOCUMENTATION SOURCE NEEDED', int),
    'client_send_interval': (20, 'refresh rate of packet sending by the server. 10Hz = ~100ms. Higher number = higher MP quality = higher bandwidth resources needed. Really high values can create connection issues', int),
    'minorating_server_trust_token': ('', 'this value is initialised when the server contacts Minorating for the first time; you may wish to record this value if migrating to another server', str),
    'proxy_plugin_port': (10003, '', int),
    'proxy_plugin_local_port': (10004, '', int),
}

CONSTANCE_CONFIG_FIELDSETS = {
    'General Settings': ('name', 'welcome_message', 'admin_password', 'minorating_grade'),
    'Advanced Settings': ('udp_port', 'tcp_port', 'http_port', 'send_buffer_size', 'recv_buffer_size', 'client_send_interval', 'minorating_server_trust_token', 'proxy_plugin_port', 'proxy_plugin_local_port'),
}

ACSERVER_HOME = '/home/acserver'
ACSERVER_BIN_DIR = os.path.join(ACSERVER_HOME, 'assetto-server')
ACSERVER_CONFIG_DIR = os.path.join(ACSERVER_HOME, 'assetto-server/cfg')
STRACKER_CONFIG_DIR = os.path.join(ACSERVER_HOME, 'stracker/cfg')
MINORATING_CONFIG_DIR = os.path.join(ACSERVER_BIN_DIR, 'plugins/minorating')
ACSERVER_FULL_ADMIN_VIEW = True
