#!/usr/bin/env python

import argparse
from acserver_libs import Inspector
import json


def argument_parser():
    parser = argparse.ArgumentParser(description='Assetto Corsa asset inspector - generates database fixtures')
    parser.add_argument('path', help='path to the Assetto Corsa content directory')
    args = parser.parse_args()
    return vars(args)


if __name__ == '__main__':
    args = argument_parser()
    i = Inspector(args['path'])
    results = i.generate_fixtures()

    print json.dumps(results, indent=4)
